### ISSUE TITLE
One of the comments is wrong for the example code

### ISSUE THREAD

**Issue by kuobenj** [sparkfun/SparkFun_9DOF_Block_for_Edison_CPP_Library#1]
The comment on line 38 is wrong.

Looking at the .h file, the default Accelerometer scale is 2G max, not 4G.

`//  Gyro scale:        245 deg/sec max
  //  Xl scale:          **4g max**
  //  Mag scale:         2 Gauss max
  //  Gyro sample rate:  95Hz`

**Comment by SFEMark** [comment]
Late reply here but I've [updated the example](https://github.com/sparkfun/SparkFun_9DOF_Block_for_Edison_CPP_Library/blob/master/SparkFun_9DOF_Edison_Block_Example.cpp#L38) to fix this incorrect comment. Closing issue.
